//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.CrossCutting.Logging.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ArabicMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArabicMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.CrossCutting.Logging.Resources.ArabicMessages", typeof(ArabicMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ArgumentException {
            get {
                return ResourceManager.GetString("ArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد خطأ فى البيانات المرسلة.
        /// </summary>
        internal static string ArgumentNullException {
            get {
                return ResourceManager.GetString("ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد خطأ فى قيم البيانات.
        /// </summary>
        internal static string ArgumentOutOfRangeException {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد مشكلة فى الاتصال بقاعدة البيانات.
        /// </summary>
        internal static string DbEntityValidationException {
            get {
                return ResourceManager.GetString("DbEntityValidationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد مشكلة فى القسمة على صفر.
        /// </summary>
        internal static string DivideByZeroException {
            get {
                return ResourceManager.GetString("DivideByZeroException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد مشكلة بقاعدة البيانات.
        /// </summary>
        internal static string EntityException {
            get {
                return ResourceManager.GetString("EntityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف غير موجود.
        /// </summary>
        internal static string FileNotFoundException {
            get {
                return ResourceManager.GetString("FileNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد مشكلة فى تحويل القيم.
        /// </summary>
        internal static string FormatException {
            get {
                return ResourceManager.GetString("FormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ غير متوقع.
        /// </summary>
        internal static string GeneralMessageError {
            get {
                return ResourceManager.GetString("GeneralMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفواً، حدث خطأ أثناء جلب العنصر.
        /// </summary>
        internal static string GET_LOOKUPSITEM_ERROR {
            get {
                return ResourceManager.GetString("GET_LOOKUPSITEM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفواً، حدث خطأ أثناء جلب العنصر.
        /// </summary>
        internal static string GET_LOOKUPSITEMS_ERROR {
            get {
                return ResourceManager.GetString("GET_LOOKUPSITEMS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفهرس غير صحيح.
        /// </summary>
        internal static string IndexOutOfRangeException {
            get {
                return ResourceManager.GetString("IndexOutOfRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ عام فى النظام برجاء المحاولة مرة أخرى .
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد مشكلة فى تحويل القيم.
        /// </summary>
        internal static string InvalidCastException {
            get {
                return ResourceManager.GetString("InvalidCastException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملية غير صحيحة.
        /// </summary>
        internal static string InvalidOperationException {
            get {
                return ResourceManager.GetString("InvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفهرس غير موجود.
        /// </summary>
        internal static string KeyNotFoundException {
            get {
                return ResourceManager.GetString("KeyNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الصلاحيات مطلوبة.
        /// </summary>
        internal static string MissingAuthorizationHeader {
            get {
                return ResourceManager.GetString("MissingAuthorizationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مخول بهذة الصلاحية أو انتهت جلستكم يمكنكم إعادة تسجيل الدخول أو مراجعة مدير الصلاحيات .
        /// </summary>
        internal static string NoAuthorization {
            get {
                return ResourceManager.GetString("NoAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء التأكد من بيانات الدخول .
        /// </summary>
        internal static string NoISAMSessionKey {
            get {
                return ResourceManager.GetString("NoISAMSessionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ غير متوقع.
        /// </summary>
        internal static string NotSupportedException {
            get {
                return ResourceManager.GetString("NotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البيانات المرسلة خاطئة برجاء التحقق من صحة البيانات المرسلة.
        /// </summary>
        internal static string NullInputData {
            get {
                return ResourceManager.GetString("NullInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد بيانات غير معرفة.
        /// </summary>
        internal static string NullReferenceException {
            get {
                return ResourceManager.GetString("NullReferenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد مشكلة فى حجم البيانات فى الذاكرة.
        /// </summary>
        internal static string OutOfMemoryException {
            get {
                return ResourceManager.GetString("OutOfMemoryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ فى العمليات على البيانات.
        /// </summary>
        internal static string OverflowException {
            get {
                return ResourceManager.GetString("OverflowException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث مشكلة فى قاعدة البيانات.
        /// </summary>
        internal static string SqlException {
            get {
                return ResourceManager.GetString("SqlException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث مشكلة فى النظام.
        /// </summary>
        internal static string StackOverflowException {
            get {
                return ResourceManager.GetString("StackOverflowException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن حذف الموضوع لارتباطه بطلبات تظلم سابقة.
        /// </summary>
        internal static string SubjectHasRequestConnected {
            get {
                return ResourceManager.GetString("SubjectHasRequestConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد نفذ الوقت الخاص بالجلسة.
        /// </summary>
        internal static string TimeoutException {
            get {
                return ResourceManager.GetString("TimeoutException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرابط غير صحيح.
        /// </summary>
        internal static string UriFormatException {
            get {
                return ResourceManager.GetString("UriFormatException", resourceCulture);
            }
        }
    }
}
