//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.CrossCutting.Logging.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnglishMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnglishMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.CrossCutting.Logging.Resources.EnglishMessages", typeof(EnglishMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument Exception.
        /// </summary>
        internal static string ArgumentException {
            get {
                return ResourceManager.GetString("ArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument Null Exception.
        /// </summary>
        internal static string ArgumentNullException {
            get {
                return ResourceManager.GetString("ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument Out Of Range Exception.
        /// </summary>
        internal static string ArgumentOutOfRangeException {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Db Entity Validation Exception.
        /// </summary>
        internal static string DbEntityValidationException {
            get {
                return ResourceManager.GetString("DbEntityValidationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divide By Zero Exception.
        /// </summary>
        internal static string DivideByZeroException {
            get {
                return ResourceManager.GetString("DivideByZeroException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Exception.
        /// </summary>
        internal static string EntityException {
            get {
                return ResourceManager.GetString("EntityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Found Exception.
        /// </summary>
        internal static string FileNotFoundException {
            get {
                return ResourceManager.GetString("FileNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Exception.
        /// </summary>
        internal static string FormatException {
            get {
                return ResourceManager.GetString("FormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error happend.
        /// </summary>
        internal static string GeneralMessageError {
            get {
                return ResourceManager.GetString("GeneralMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفواً، حدث خطأ أثناء جلب العنصر.
        /// </summary>
        internal static string GET_LOOKUPSITEM_ERROR {
            get {
                return ResourceManager.GetString("GET_LOOKUPSITEM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفواً، حدث خطأ أثناء جلب العنصر.
        /// </summary>
        internal static string GET_LOOKUPSITEMS_ERROR {
            get {
                return ResourceManager.GetString("GET_LOOKUPSITEMS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Out Of Range Exception.
        /// </summary>
        internal static string IndexOutOfRangeException {
            get {
                return ResourceManager.GetString("IndexOutOfRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error , Please  Try Agin Later .
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Cast Exception.
        /// </summary>
        internal static string InvalidCastException {
            get {
                return ResourceManager.GetString("InvalidCastException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construct API Result: Invalid Failure HttpStatusCode.
        /// </summary>
        internal static string InvalidFailureHttpStatusCode {
            get {
                return ResourceManager.GetString("InvalidFailureHttpStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Operation Exception.
        /// </summary>
        internal static string InvalidOperationException {
            get {
                return ResourceManager.GetString("InvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construct API Result: Invalid Internal Server Error HttpStatusCode.
        /// </summary>
        internal static string InvalidServerErrorHttpStatusCode {
            get {
                return ResourceManager.GetString("InvalidServerErrorHttpStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construct API Result: Invalid Success HttpStatusCode.
        /// </summary>
        internal static string InvalidSuccessHttpStatusCode {
            get {
                return ResourceManager.GetString("InvalidSuccessHttpStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Not Found Exception.
        /// </summary>
        internal static string KeyNotFoundException {
            get {
                return ResourceManager.GetString("KeyNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Authorization Header.
        /// </summary>
        internal static string MissingAuthorizationHeader {
            get {
                return ResourceManager.GetString("MissingAuthorizationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Authorization Privillage , Please  try to login again or contact with  System Administrator .
        /// </summary>
        internal static string NoAuthorization {
            get {
                return ResourceManager.GetString("NoAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Session Key  , Please Login Again .
        /// </summary>
        internal static string NoISAMSessionKey {
            get {
                return ResourceManager.GetString("NoISAMSessionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Supported Exception.
        /// </summary>
        internal static string NotSupportedException {
            get {
                return ResourceManager.GetString("NotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Data Not Correct , Please Check sent Data and send again.
        /// </summary>
        internal static string NullInputData {
            get {
                return ResourceManager.GetString("NullInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null Reference Exception.
        /// </summary>
        internal static string NullReferenceException {
            get {
                return ResourceManager.GetString("NullReferenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Of Memory Exception.
        /// </summary>
        internal static string OutOfMemoryException {
            get {
                return ResourceManager.GetString("OutOfMemoryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overflow Exception.
        /// </summary>
        internal static string OverflowException {
            get {
                return ResourceManager.GetString("OverflowException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sql Exception.
        /// </summary>
        internal static string SqlException {
            get {
                return ResourceManager.GetString("SqlException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Over flow Exception.
        /// </summary>
        internal static string StackOverflowException {
            get {
                return ResourceManager.GetString("StackOverflowException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot delete subject that has Requests connected to it.
        /// </summary>
        internal static string SubjectHasRequestConnected {
            get {
                return ResourceManager.GetString("SubjectHasRequestConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time out Exception.
        /// </summary>
        internal static string TimeoutException {
            get {
                return ResourceManager.GetString("TimeoutException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construct API Result: Unknown HttpStatusCode.
        /// </summary>
        internal static string UnknownHttpStatusCode {
            get {
                return ResourceManager.GetString("UnknownHttpStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri Format Exception.
        /// </summary>
        internal static string UriFormatException {
            get {
                return ResourceManager.GetString("UriFormatException", resourceCulture);
            }
        }
    }
}
